/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCostsRouteImport } from './routes/admin.costs'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStoriesRouteImport } from './routes/admin.stories'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ReadStoryIdRouteImport } from './routes/read.$storyId'
import { Route as AdminStoriesNewRouteImport } from './routes/admin.stories.new'
import { Route as AdminStoriesStoryIdCanvasRouteImport } from './routes/admin.stories.$storyId.canvas'
import { Route as AdminStoriesStoryIdEditRouteImport } from './routes/admin.stories.$storyId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCostsRoute = AdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ReadStoryIdRoute = ReadStoryIdRouteImport.update({
  id: '/read/$storyId',
  path: '/read/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStoriesNewRoute = AdminStoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminStoriesRoute,
} as any)
const AdminStoriesStoryIdCanvasRoute =
  AdminStoriesStoryIdCanvasRouteImport.update({
    id: '/$storyId/canvas',
    path: '/$storyId/canvas',
    getParentRoute: () => AdminStoriesRoute,
  } as any)
const AdminStoriesStoryIdEditRoute = AdminStoriesStoryIdEditRouteImport.update({
  id: '/$storyId/edit',
  path: '/$storyId/edit',
  getParentRoute: () => AdminStoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/legal': typeof LegalRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/admin/stories/$storyId/canvas': typeof AdminStoriesStoryIdCanvasRoute
  '/admin/stories/$storyId/edit': typeof AdminStoriesStoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/legal': typeof LegalRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/admin/stories/$storyId/canvas': typeof AdminStoriesStoryIdCanvasRoute
  '/admin/stories/$storyId/edit': typeof AdminStoriesStoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/legal': typeof LegalRoute
  '/settings': typeof SettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/read/$storyId': typeof ReadStoryIdRoute
  '/admin/stories/new': typeof AdminStoriesNewRoute
  '/admin/stories/$storyId/canvas': typeof AdminStoriesStoryIdCanvasRoute
  '/admin/stories/$storyId/edit': typeof AdminStoriesStoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/legal'
    | '/settings'
    | '/admin/analytics'
    | '/admin/costs'
    | '/admin/finance'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/users'
    | '/read/$storyId'
    | '/admin/stories/new'
    | '/admin/stories/$storyId/canvas'
    | '/admin/stories/$storyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/legal'
    | '/settings'
    | '/admin/analytics'
    | '/admin/costs'
    | '/admin/finance'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/users'
    | '/read/$storyId'
    | '/admin/stories/new'
    | '/admin/stories/$storyId/canvas'
    | '/admin/stories/$storyId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/legal'
    | '/settings'
    | '/admin/analytics'
    | '/admin/costs'
    | '/admin/finance'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/users'
    | '/read/$storyId'
    | '/admin/stories/new'
    | '/admin/stories/$storyId/canvas'
    | '/admin/stories/$storyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LegalRoute: typeof LegalRoute
  SettingsRoute: typeof SettingsRoute
  ReadStoryIdRoute: typeof ReadStoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/costs': {
      id: '/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AdminCostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/read/$storyId': {
      id: '/read/$storyId'
      path: '/read/$storyId'
      fullPath: '/read/$storyId'
      preLoaderRoute: typeof ReadStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stories/new': {
      id: '/admin/stories/new'
      path: '/new'
      fullPath: '/admin/stories/new'
      preLoaderRoute: typeof AdminStoriesNewRouteImport
      parentRoute: typeof AdminStoriesRoute
    }
    '/admin/stories/$storyId/canvas': {
      id: '/admin/stories/$storyId/canvas'
      path: '/$storyId/canvas'
      fullPath: '/admin/stories/$storyId/canvas'
      preLoaderRoute: typeof AdminStoriesStoryIdCanvasRouteImport
      parentRoute: typeof AdminStoriesRoute
    }
    '/admin/stories/$storyId/edit': {
      id: '/admin/stories/$storyId/edit'
      path: '/$storyId/edit'
      fullPath: '/admin/stories/$storyId/edit'
      preLoaderRoute: typeof AdminStoriesStoryIdEditRouteImport
      parentRoute: typeof AdminStoriesRoute
    }
  }
}

interface AdminStoriesRouteChildren {
  AdminStoriesNewRoute: typeof AdminStoriesNewRoute
  AdminStoriesStoryIdCanvasRoute: typeof AdminStoriesStoryIdCanvasRoute
  AdminStoriesStoryIdEditRoute: typeof AdminStoriesStoryIdEditRoute
}

const AdminStoriesRouteChildren: AdminStoriesRouteChildren = {
  AdminStoriesNewRoute: AdminStoriesNewRoute,
  AdminStoriesStoryIdCanvasRoute: AdminStoriesStoryIdCanvasRoute,
  AdminStoriesStoryIdEditRoute: AdminStoriesStoryIdEditRoute,
}

const AdminStoriesRouteWithChildren = AdminStoriesRoute._addFileChildren(
  AdminStoriesRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCostsRoute: typeof AdminCostsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoriesRoute: typeof AdminStoriesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCostsRoute: AdminCostsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoriesRoute: AdminStoriesRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LegalRoute: LegalRoute,
  SettingsRoute: SettingsRoute,
  ReadStoryIdRoute: ReadStoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
